FROM nginx:1.20.2

COPY ./images/nginx/conf/nginx.conf /etc/nginx/
COPY ./hosts/ /etc/nginx/conf.d/
COPY ./images/nginx/conf/upstream.conf /etc/nginx/conf.d/

RUN usermod -u 1000 www-data

CMD ["nginx"]

EXPOSE 80 443
