FROM phpdockerio/php:8.2-fpm

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    php8.2-memcached \
    php8.2-memcache \
    php8.2-mbstring \
    php8.2-mysqli \
    php8.2-intl \
    php8.2-xdebug \
    php8.2-interbase \
    php8.2-soap \
    php8.2-gd \
    php8.2-imagick \
    php8.2-opcache \
    php8.2-zip \
    php8.2-bcmath \
    php-pear php8.2-dev libmcrypt-dev gcc make autoconf libc-dev pkg-config \
    && pecl install mcrypt-1.0.4 \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* \

RUN docker-php-ext-install mysqli
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./images/php/php.ini /etc/php/8.2/fpm/conf.d/90-php.ini
COPY ./images/php/php.ini /etc/php/8.2/cli/conf.d/90-php.ini

RUN usermod -u 1000 www-data

WORKDIR /var/www/

EXPOSE 9000
